sudo: required

# whitelist
branches:
  only:
   - gh-pages   

language: node_js
node_js:
  - "4.1"

before_script:
  - npm install -g jsonschema-cli

script: validateJson -d projects.json -s projects-schema.json


